rm altcoins with broken dependencies for python 3.13
```
pip install git+https://github.com/RitoProject/x21s_hash
Collecting git+https://github.com/RitoProject/x21s_hash
  Cloning https://github.com/RitoProject/x21s_hash to /tmp/pip-req-build-gqb9hikj
  Running command git clone --filter=blob:none --quiet https://github.com/RitoProject/x21s_hash /tmp/pip-req-build-gqb9hikj
  Resolved https://github.com/RitoProject/x21s_hash to commit 8a8c50d9182c361ee822f4aa44c43444d02733d6
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: x21s_hash
  Building wheel for x21s_hash (setup.py): started
  Building wheel for x21s_hash (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      sph/luffa.c:156:22: warning: ‘RC34’ defined but not used [-Wunused-const-variable=]
        156 | static const sph_u32 RC34[8] = {
            |                      ^~~~
      sph/luffa.c:148:22: warning: ‘RC30’ defined but not used [-Wunused-const-variable=]
        148 | static const sph_u32 RC30[8] = {
            |                      ^~~~
      sph/luffa.c:106:22: warning: ‘RC14’ defined but not used [-Wunused-const-variable=]
        106 | static const sph_u32 RC14[8] = {
            |                      ^~~~
      sph/luffa.c:98:22: warning: ‘RC10’ defined but not used [-Wunused-const-variable=]
         98 | static const sph_u32 RC10[8] = {
            |                      ^~~~
      sph/luffa.c:90:22: warning: ‘RC04’ defined but not used [-Wunused-const-variable=]
         90 | static const sph_u32 RC04[8] = {
            |                      ^~~~
      sph/luffa.c:82:22: warning: ‘RC00’ defined but not used [-Wunused-const-variable=]
         82 | static const sph_u32 RC00[8] = {
            |                      ^~~~
      sph/sha2.c: In function ‘sha256d’:
      sph/sha2.c:218:32: error: implicit declaration of function ‘be32dec’ [-Wimplicit-function-declaration]
        218 |                         T[i] = be32dec(T + i);
            |                                ^~~~~~~
      sph/sha2.c:227:17: error: implicit declaration of function ‘be32enc’ [-Wimplicit-function-declaration]
        227 |                 be32enc((uint32_t *)hash + i, T[i]);
            |                 ^~~~~~~
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for x21s_hash
  Running setup.py clean for x21s_hash
Failed to build x21s_hash
ERROR: Failed to build installable wheels for some pyproject.toml based projects (x21s_hash)
```

```
pip install bell-yespower
Collecting bell-yespower
  Downloading bell_yespower-1.0.3.tar.gz (20 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Building wheel for bell-yespower (setup.py): started
  Building wheel for bell-yespower (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'bell_yespower' extension
      creating build/temp.linux-x86_64-cpython-313
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I. -I/usr/include/python3.13 -c sha256.c -o build/temp.linux-x86_64-cpython-313/sha256.o -O2 -funroll-loops -fomit-frame-pointer
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I. -I/usr/include/python3.13 -c yespower-module.c -o build/temp.linux-x86_64-cpython-313/yespower-module.o -O2 -funroll-loops -fomit-frame-pointer
      yespower-module.c: In function ‘yespower_getpowhash’:
      yespower-module.c:18:5: error: implicit declaration of function ‘yespower_hash’; did you mean ‘yespower_getpowhash’? [-Wimplicit-function-declaration]
         18 |     yespower_hash((char *)PyBytes_AsString((PyObject*) input), output);
            |     ^~~~~~~~~~~~~
            |     yespower_getpowhash
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py clean for bell-yespower
ERROR: Failed to build installable wheels for some pyproject.toml based projects (bell-yespower)
```

```
pip install cpupower
Collecting cpupower
  Downloading cpupower-1.0.1.tar.gz (20 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Building wheel for cpupower (setup.py): started
  Building wheel for cpupower (setup.py): finished with status 'error'
  ERROR: Failed building wheel for cpupower
  Running setup.py clean for cpupower
ERROR: Failed to build installable wheels for some pyproject.toml based projects (cpupower)
```

```
pip install bitweb_yespower==1.0.5
Collecting bitweb_yespower==1.0.5
  Downloading bitweb_yespower-1.0.5.tar.gz (22 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Building wheel for bitweb_yespower (setup.py): started
  Building wheel for bitweb_yespower (setup.py): finished with status 'error'
  ERROR: Failed building wheel for bitweb_yespower
  Running setup.py clean for bitweb_yespower
ERROR: Failed to build installable wheels for some pyproject.toml based projects (bitweb_yespower)
```