fix a bug in peer discovery
closes https://github.com/spesmilo/electrumx/pull/244

- this also adds some generic protection so that e-x now tolerates peer discovery dying in isolation

example stack trace:
```
INFO:Prefetcher:cancelled; prefetcher stopping
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/home/user/wspace/electrumx/./electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/wspace/electrumx/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/home/user/wspace/electrumx/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/home/user/wspace/electrumx/electrumx/server/controller.py", line 134, in serve
    async with OldTaskGroup() as group:
  File "/home/user/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/user/wspace/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/user/wspace/electrumx/electrumx/server/session.py", line 676, in serve
    async with self._task_group as group:
  File "/home/user/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/user/wspace/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/user/wspace/electrumx/electrumx/server/peers.py", line 477, in discover_peers
    async with self.group as group:
  File "/home/user/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/user/wspace/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/user/wspace/electrumx/electrumx/server/peers.py", line 246, in _monitor_peer
    if await self._should_drop_peer(peer):
  File "/home/user/wspace/electrumx/electrumx/server/peers.py", line 289, in _should_drop_peer
    await self._verify_peer(session, peer)
  File "/home/user/wspace/electrumx/electrumx/server/peers.py", line 387, in _verify_peer
    async with OldTaskGroup() as g:
  File "/home/user/.local/lib/python3.10/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/home/user/wspace/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/home/user/wspace/electrumx/electrumx/server/peers.py", line 434, in _send_server_features
    hosts = [host.lower() for host in features.get('hosts', {})]  #
TypeError: 'int' object is not iterable
```