aiorpcx: adapt TaskGroup._add_task monkey-patch to upstream fix
- upstream fix is at https://github.com/kyuupichan/aiorpcX/commit/a0be71c5671b07e02bedc51d7efaecda86f05128 ,
  but it's not yet released
- prev monkey-patch was causing issues if used with aiorpcx that already has the upstream fix:

```
INFO:SessionManager:TCP server listening on 127.0.0.1:51001
INFO:SessionManager:SSL server listening on 127.0.0.1:51002
INFO:PeerManager:peer discovery: ON
INFO:PeerManager:announce ourself: True
INFO:PeerManager:my clearnet self: None
INFO:PeerManager:force use of proxy: False
INFO:PeerManager:beginning peer discovery...
INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
Exception in callback TaskGroup._on_done(<Task finishe...> result=None>)
handle: <Handle TaskGroup._on_done(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/wspace/aiorpcX/aiorpcx/curio.py", line 147, in _on_done
    self.tasks.remove(task)
KeyError: <Task finished name='Task-29' coro=<PeerManager._refresh_blacklist() done, defined at /home/user/wspace/electrumx/electrumx/server/peers.py:144> result=None>
Exception in callback TaskGroup._on_done(<Task finishe...> result=None>)
handle: <Handle TaskGroup._on_done(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/wspace/aiorpcX/aiorpcx/curio.py", line 147, in _on_done
    self.tasks.remove(task)
KeyError: <Task finished name='Task-31' coro=<PeerManager._import_peers() done, defined at /home/user/wspace/electrumx/electrumx/server/peers.py:135> result=None>
INFO:PeerManager:detected SOCKS5 proxy at localhost:9050, auth: none
Exception in callback TaskGroup._on_done(<Task finishe...> result=None>)
handle: <Handle TaskGroup._on_done(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/wspace/aiorpcX/aiorpcx/curio.py", line 147, in _on_done
    self.tasks.remove(task)
KeyError: <Task finished name='Task-30' coro=<PeerManager._detect_proxy() done, defined at /home/user/wspace/electrumx/electrumx/server/peers.py:182> result=None>
```